// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.DNSLookup
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("premium")]
        public Premium Premium { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("domain")]
        public string Domain { get; set; }

        [JsonProperty("records")]
        public Records Records { get; set; }

        [JsonProperty("summary")]
        public Summary Summary { get; set; }
    }

    public partial class Records
    {
        [JsonProperty("A")]
        public string[] A { get; set; }

        [JsonProperty("MX")]
        public Mx[] Mx { get; set; }

        [JsonProperty("NS")]
        public string[] Ns { get; set; }

        [JsonProperty("SOA")]
        public Soa Soa { get; set; }

        [JsonProperty("TXT")]
        public string[] Txt { get; set; }
    }

    public partial class Mx
    {
        [JsonProperty("exchange")]
        public string Exchange { get; set; }

        [JsonProperty("priority")]
        public long? Priority { get; set; }
    }

    public partial class Soa
    {
        [JsonProperty("nsname")]
        public string Nsname { get; set; }

        [JsonProperty("hostmaster")]
        public string Hostmaster { get; set; }

        [JsonProperty("serial")]
        public long? Serial { get; set; }

        [JsonProperty("refresh")]
        public long? Refresh { get; set; }

        [JsonProperty("retry")]
        public long? Retry { get; set; }

        [JsonProperty("expire")]
        public long? Expire { get; set; }

        [JsonProperty("minttl")]
        public long? Minttl { get; set; }
    }

    public partial class Summary
    {
        [JsonProperty("hasIPv6")]
        public bool? HasIPv6 { get; set; }

        [JsonProperty("hasMailServers")]
        public bool? HasMailServers { get; set; }

        [JsonProperty("hasSPF")]
        public bool? HasSpf { get; set; }
    }

    public partial class Premium
    {
        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("upgrade_url")]
        public Uri UpgradeUrl { get; set; }

        [JsonProperty("locked_fields")]
        public string[] LockedFields { get; set; }
    }
}
